import { NextRequest } from "next/server";
import { requireAuth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ok, unauthorized, notFound } from "@/lib/response";
import type { FormConfig, TableConfig } from "@/types/config";

function generateReadme(appName: string, config: { type: string; title?: string }): string {
  return `# ${appName}

Generated by AppForge.

## Config Type

\`${config.type}\` — ${config.title ?? appName}

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

## Environment

\`\`\`
DATABASE_URL=postgresql://...
\`\`\`
`;
}

function generateFormComponent(config: FormConfig): string {
  const fields = config.fields
    .map(
      (f) =>
        `      <div>
        <label>${f.label}</label>
        <input type="${f.type}" name="${f.name}" ${f.required ? "required" : ""} />
      </div>`
    )
    .join("\n");

  return `export default function ${config.title.replace(/\s+/g, "")}Form() {
  return (
    <form>
      <h1>${config.title}</h1>
${fields}
      <button type="submit">${config.submitLabel ?? "Submit"}</button>
    </form>
  );
}
`;
}

function generateTableComponent(config: TableConfig): string {
  const headers = config.columns
    .map((c) => `        <th>${c.label}</th>`)
    .join("\n");
  const cells = config.columns
    .map((c) => `        <td>{{row.${c.key}}}</td>`)
    .join("\n");

  return `export default function ${config.title.replace(/\s+/g, "")}Table({ data = [] }) {
  return (
    <table>
      <thead>
        <tr>
${headers}
        </tr>
      </thead>
      <tbody>
        {data.map((row, i) => (
          <tr key={i}>
${cells}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
`;
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ appId: string }> }
) {
  const user = await requireAuth();
  if (!user) return unauthorized();

  const { appId } = await params;

  const app = await prisma.app.findFirst({
    where: { id: appId, userId: user.id },
  });
  if (!app) return notFound("App");

  const config = app.config as { type: string; title?: string };

  let componentCode = "";
  if (config.type === "form") {
    componentCode = generateFormComponent(config as unknown as FormConfig);
  } else if (config.type === "table") {
    componentCode = generateTableComponent(config as unknown as TableConfig);
  }

  const files: Record<string, string> = {
    "README.md": generateReadme(app.name, config),
    "config.json": JSON.stringify(app.config, null, 2),
    [`components/${app.name.replace(/\s+/g, "")}.jsx`]: componentCode,
    "package.json": JSON.stringify(
      {
        name: app.slug,
        version: "0.1.0",
        private: true,
        scripts: { dev: "next dev", build: "next build" },
        dependencies: { next: "^15", react: "^18", "react-dom": "^18" },
      },
      null,
      2
    ),
  };

  return ok({
    appName: app.name,
    slug: app.slug,
    files,
    totalFiles: Object.keys(files).length,
  });
}
